# Generated by Django 3.2.9 on 2021-11-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='subject',
            new_name='first_name',
        ),
    ]
