# Generated by Django 3.2.9 on 2021-11-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('picture', models.FileField(upload_to='pictures/')),
                ('dor', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('transmission', models.TextField(max_length=50)),
                ('engine', models.FloatField(max_length=50)),
            ],
        ),
    ]
